Run stdlib's pdict_SUITE and maps_SUITE as tests
Proxy BIFs erlang:now/0, erlang:system_info/1, erlang:process_info/2.

Proxy the TRAP_EXIT status flag.

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -16,10 +16,21 @@ $TEST_ERL -eval 'case unit:test() of error -> halt(1); _ -> init:stop() end' || 
 
 TESTS=`$ERL -s regressions working -s erlang halt`
 
+TS_MODS="$@"
+
 for t in $TESTS; do
     sleep 1 # We do what we can to prevent bus lockups, even voodoo like this
     echo " --> Running regressions:$t()"
     $TEST_ERL -s regressions run $t || {
+        echo "FAILURE"
+        exit 1
+    }
+done
+
+for m in $TS_MODS; do
+    sleep 1 # We do what we can to prevent bus lockups, even voodoo like this
+    echo " ==> Running ts_epi:run([$m])"
+    $TEST_ERL -s ts_epi run $m || {
         echo "FAILURE"
         exit 1
     }
